[package]
name = "kokoro-g2p"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
fancy-regex = "0.14"
flate2 = "1"
jieba-rs = "0.10"
jpreprocess = { version = "0.15", features = ["naist-jdic"] }
jpreprocess-core = "0.15"
unicode-normalization = "0.1"

[build-dependencies]
flate2 = "1"
